// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJhoc5qscEVsUAk3KnghlDpQpD5XD9Sk4',
    appId: '1:231195648290:web:e762931e2e1379e200857b',
    messagingSenderId: '231195648290',
    projectId: 'note-time-project',
    authDomain: 'note-time-project.firebaseapp.com',
    storageBucket: 'note-time-project.appspot.com',
    measurementId: 'G-CDFL7VPRQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL11snxzTRspZhSkgiQYpfhSUyqrIw0xA',
    appId: '1:231195648290:android:6b10dc35877f4a4400857b',
    messagingSenderId: '231195648290',
    projectId: 'note-time-project',
    storageBucket: 'note-time-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfm8_ZEJKX2HGBcggz4EawLVvl2PnhM60',
    appId: '1:231195648290:ios:8fb4ab6793af504500857b',
    messagingSenderId: '231195648290',
    projectId: 'note-time-project',
    storageBucket: 'note-time-project.appspot.com',
    iosClientId: '231195648290-rlq2uti86mf4u674mr7085dcnea0evme.apps.googleusercontent.com',
    iosBundleId: 'com.humanclockworks.notetime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfm8_ZEJKX2HGBcggz4EawLVvl2PnhM60',
    appId: '1:231195648290:ios:dfef8fecdcfb1f6200857b',
    messagingSenderId: '231195648290',
    projectId: 'note-time-project',
    storageBucket: 'note-time-project.appspot.com',
    iosClientId: '231195648290-r2l7aeqpujqrb5nu6hlffjtb172ccss2.apps.googleusercontent.com',
    iosBundleId: 'com.humanclockworks.notetime.RunnerTests',
  );
}
